In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys as sys
import seaborn as sns
import scipy as cp

In [2]:
#import dataset
data = pd.read_csv(r'Iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
data = data.drop(['Id'],axis=1)        #Dropping the Id column

In [4]:
#Label Encoding the targt class
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(['Iris-setosa','Iris-versicolor','Iris-virginica'])
print(data.Species)
data['Species']=le.transform(data['Species'])

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object


In [5]:
#Splitting the dataset inti dependent and independent(target class) features
x = data.drop('Species',axis=1)
y = data['Species']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int32

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
print(f'Rows in train set: {len(x_train)}\nRows in test set: {len(x_test)}')

Rows in train set: 120
Rows in test set: 30


In [7]:
#Building Support Vector Classifier model
from sklearn.svm import SVC
svm_model = SVC()
classifier = svm_model.fit(x_train,y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy for multinomial logistic regression: ",accuracy_score(y_test, y_pred)*100,'%')

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy for multinomial logistic regression:  100.0 %


In [8]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
a = accuracy_score(y_test,y_pred)*100
a

100.0

In [10]:
x_result = np.array([[4,3,1,1]])

prediction = classifier.predict(x_result)
print(prediction)

[0]


In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
lr = LogisticRegression(multi_class = 'multinomial', solver = 'newton-cg')
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy for multinomial logistic regression: ",accuracy_score(y_test, y_pred)*100,'%')

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy for multinomial logistic regression:  100.0 %
